// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: docs.proto

package docspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Docs_Source_FullMethodName = "/anyserver.docs.Docs/Source"
)

// DocsClient is the client API for Docs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocsClient interface {
	// Browse embedded source code. When path is a directory, streams Path entries.
	// When path is a file, streams typed content chunks.
	Source(ctx context.Context, in *SourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SourceCode], error)
}

type docsClient struct {
	cc grpc.ClientConnInterface
}

func NewDocsClient(cc grpc.ClientConnInterface) DocsClient {
	return &docsClient{cc}
}

func (c *docsClient) Source(ctx context.Context, in *SourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SourceCode], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Docs_ServiceDesc.Streams[0], Docs_Source_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SourceRequest, SourceCode]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Docs_SourceClient = grpc.ServerStreamingClient[SourceCode]

// DocsServer is the server API for Docs service.
// All implementations must embed UnimplementedDocsServer
// for forward compatibility.
type DocsServer interface {
	// Browse embedded source code. When path is a directory, streams Path entries.
	// When path is a file, streams typed content chunks.
	Source(*SourceRequest, grpc.ServerStreamingServer[SourceCode]) error
	mustEmbedUnimplementedDocsServer()
}

// UnimplementedDocsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocsServer struct{}

func (UnimplementedDocsServer) Source(*SourceRequest, grpc.ServerStreamingServer[SourceCode]) error {
	return status.Error(codes.Unimplemented, "method Source not implemented")
}
func (UnimplementedDocsServer) mustEmbedUnimplementedDocsServer() {}
func (UnimplementedDocsServer) testEmbeddedByValue()              {}

// UnsafeDocsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocsServer will
// result in compilation errors.
type UnsafeDocsServer interface {
	mustEmbedUnimplementedDocsServer()
}

func RegisterDocsServer(s grpc.ServiceRegistrar, srv DocsServer) {
	// If the following call panics, it indicates UnimplementedDocsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Docs_ServiceDesc, srv)
}

func _Docs_Source_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SourceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocsServer).Source(m, &grpc.GenericServerStream[SourceRequest, SourceCode]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Docs_SourceServer = grpc.ServerStreamingServer[SourceCode]

// Docs_ServiceDesc is the grpc.ServiceDesc for Docs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Docs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anyserver.docs.Docs",
	HandlerType: (*DocsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Source",
			Handler:       _Docs_Source_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "docs.proto",
}
