// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: docs.proto

package docspb

import (
	v1 "github.com/accretional/anyserver/proto/openformat/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRequest) Reset() {
	*x = SourceRequest{}
	mi := &file_docs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRequest) ProtoMessage() {}

func (x *SourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRequest.ProtoReflect.Descriptor instead.
func (*SourceRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{0}
}

func (x *SourceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SourceCode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*SourceCode_Path
	//	*SourceCode_Code
	//	*SourceCode_Media
	//	*SourceCode_Data
	//	*SourceCode_Binary
	Kind          isSourceCode_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceCode) Reset() {
	*x = SourceCode{}
	mi := &file_docs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceCode) ProtoMessage() {}

func (x *SourceCode) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceCode.ProtoReflect.Descriptor instead.
func (*SourceCode) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{1}
}

func (x *SourceCode) GetKind() isSourceCode_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *SourceCode) GetPath() *PathEntry {
	if x != nil {
		if x, ok := x.Kind.(*SourceCode_Path); ok {
			return x.Path
		}
	}
	return nil
}

func (x *SourceCode) GetCode() *Code {
	if x != nil {
		if x, ok := x.Kind.(*SourceCode_Code); ok {
			return x.Code
		}
	}
	return nil
}

func (x *SourceCode) GetMedia() *Media {
	if x != nil {
		if x, ok := x.Kind.(*SourceCode_Media); ok {
			return x.Media
		}
	}
	return nil
}

func (x *SourceCode) GetData() *Data {
	if x != nil {
		if x, ok := x.Kind.(*SourceCode_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *SourceCode) GetBinary() *Binary {
	if x != nil {
		if x, ok := x.Kind.(*SourceCode_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

type isSourceCode_Kind interface {
	isSourceCode_Kind()
}

type SourceCode_Path struct {
	Path *PathEntry `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type SourceCode_Code struct {
	Code *Code `protobuf:"bytes,2,opt,name=code,proto3,oneof"`
}

type SourceCode_Media struct {
	Media *Media `protobuf:"bytes,3,opt,name=media,proto3,oneof"`
}

type SourceCode_Data struct {
	Data *Data `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

type SourceCode_Binary struct {
	Binary *Binary `protobuf:"bytes,5,opt,name=binary,proto3,oneof"`
}

func (*SourceCode_Path) isSourceCode_Kind() {}

func (*SourceCode_Code) isSourceCode_Kind() {}

func (*SourceCode_Media) isSourceCode_Kind() {}

func (*SourceCode_Data) isSourceCode_Kind() {}

func (*SourceCode_Binary) isSourceCode_Kind() {}

// Directory listing entry.
type PathEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathEntry) Reset() {
	*x = PathEntry{}
	mi := &file_docs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathEntry) ProtoMessage() {}

func (x *PathEntry) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathEntry.ProtoReflect.Descriptor instead.
func (*PathEntry) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{2}
}

func (x *PathEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PathEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *PathEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Source code or text file chunk. Sequential chunks concatenate to full file.
type Code struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      string                 `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Code) Reset() {
	*x = Code{}
	mi := &file_docs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Code) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Code) ProtoMessage() {}

func (x *Code) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Code.ProtoReflect.Descriptor instead.
func (*Code) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{3}
}

func (x *Code) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

func (x *Code) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Media file chunk (image, audio, video, etc.).
type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []byte                 `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      *v1.MimeType           `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_docs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{4}
}

func (x *Media) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *Media) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Media) GetMimeType() *v1.MimeType {
	if x != nil {
		return x.MimeType
	}
	return nil
}

// Generic streamed data for large files or mixed content.
type Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Data_TypeUrl
	//	*Data_Text
	//	*Data_FileName
	//	*Data_More
	Kind          isData_Kind `protobuf_oneof:"kind"`
	Contents      []byte      `protobuf:"bytes,5,opt,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_docs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{5}
}

func (x *Data) GetKind() isData_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Data) GetTypeUrl() string {
	if x != nil {
		if x, ok := x.Kind.(*Data_TypeUrl); ok {
			return x.TypeUrl
		}
	}
	return ""
}

func (x *Data) GetText() string {
	if x != nil {
		if x, ok := x.Kind.(*Data_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Data) GetFileName() string {
	if x != nil {
		if x, ok := x.Kind.(*Data_FileName); ok {
			return x.FileName
		}
	}
	return ""
}

func (x *Data) GetMore() bool {
	if x != nil {
		if x, ok := x.Kind.(*Data_More); ok {
			return x.More
		}
	}
	return false
}

func (x *Data) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type isData_Kind interface {
	isData_Kind()
}

type Data_TypeUrl struct {
	TypeUrl string `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3,oneof"`
}

type Data_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type Data_FileName struct {
	FileName string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3,oneof"`
}

type Data_More struct {
	More bool `protobuf:"varint,4,opt,name=more,proto3,oneof"` // more chunks follow
}

func (*Data_TypeUrl) isData_Kind() {}

func (*Data_Text) isData_Kind() {}

func (*Data_FileName) isData_Kind() {}

func (*Data_More) isData_Kind() {}

// Opaque binary data (triggers download over HTTP).
type Binary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []byte                 `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binary) Reset() {
	*x = Binary{}
	mi := &file_docs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binary) ProtoMessage() {}

func (x *Binary) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binary.ProtoReflect.Descriptor instead.
func (*Binary) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{6}
}

func (x *Binary) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

var File_docs_proto protoreflect.FileDescriptor

const file_docs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"docs.proto\x12\x0eanyserver.docs\x1a\x1cgoogle/api/annotations.proto\x1a\x18openformat/v1/mime.proto\"#\n" +
	"\rSourceRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xfe\x01\n" +
	"\n" +
	"SourceCode\x12/\n" +
	"\x04path\x18\x01 \x01(\v2\x19.anyserver.docs.PathEntryH\x00R\x04path\x12*\n" +
	"\x04code\x18\x02 \x01(\v2\x14.anyserver.docs.CodeH\x00R\x04code\x12-\n" +
	"\x05media\x18\x03 \x01(\v2\x15.anyserver.docs.MediaH\x00R\x05media\x12*\n" +
	"\x04data\x18\x04 \x01(\v2\x14.anyserver.docs.DataH\x00R\x04data\x120\n" +
	"\x06binary\x18\x05 \x01(\v2\x16.anyserver.docs.BinaryH\x00R\x06binaryB\x06\n" +
	"\x04kind\"J\n" +
	"\tPathEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\">\n" +
	"\x04Code\x12\x1a\n" +
	"\bcontents\x18\x01 \x01(\tR\bcontents\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"u\n" +
	"\x05Media\x12\x1a\n" +
	"\bcontents\x18\x01 \x01(\fR\bcontents\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x124\n" +
	"\tmime_type\x18\x03 \x01(\v2\x17.openformat.v1.MimeTypeR\bmimeType\"\x92\x01\n" +
	"\x04Data\x12\x1b\n" +
	"\btype_url\x18\x01 \x01(\tH\x00R\atypeUrl\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x12\x1d\n" +
	"\tfile_name\x18\x03 \x01(\tH\x00R\bfileName\x12\x14\n" +
	"\x04more\x18\x04 \x01(\bH\x00R\x04more\x12\x1a\n" +
	"\bcontents\x18\x05 \x01(\fR\bcontentsB\x06\n" +
	"\x04kind\"$\n" +
	"\x06Binary\x12\x1a\n" +
	"\bcontents\x18\x01 \x01(\fR\bcontents2h\n" +
	"\x04Docs\x12`\n" +
	"\x06Source\x12\x1d.anyserver.docs.SourceRequest\x1a\x1a.anyserver.docs.SourceCode\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/source/{path=**}0\x01B4Z2github.com/accretional/anyserver/proto/docs;docspbb\x06proto3"

var (
	file_docs_proto_rawDescOnce sync.Once
	file_docs_proto_rawDescData []byte
)

func file_docs_proto_rawDescGZIP() []byte {
	file_docs_proto_rawDescOnce.Do(func() {
		file_docs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_rawDesc), len(file_docs_proto_rawDesc)))
	})
	return file_docs_proto_rawDescData
}

var file_docs_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_docs_proto_goTypes = []any{
	(*SourceRequest)(nil), // 0: anyserver.docs.SourceRequest
	(*SourceCode)(nil),    // 1: anyserver.docs.SourceCode
	(*PathEntry)(nil),     // 2: anyserver.docs.PathEntry
	(*Code)(nil),          // 3: anyserver.docs.Code
	(*Media)(nil),         // 4: anyserver.docs.Media
	(*Data)(nil),          // 5: anyserver.docs.Data
	(*Binary)(nil),        // 6: anyserver.docs.Binary
	(*v1.MimeType)(nil),   // 7: openformat.v1.MimeType
}
var file_docs_proto_depIdxs = []int32{
	2, // 0: anyserver.docs.SourceCode.path:type_name -> anyserver.docs.PathEntry
	3, // 1: anyserver.docs.SourceCode.code:type_name -> anyserver.docs.Code
	4, // 2: anyserver.docs.SourceCode.media:type_name -> anyserver.docs.Media
	5, // 3: anyserver.docs.SourceCode.data:type_name -> anyserver.docs.Data
	6, // 4: anyserver.docs.SourceCode.binary:type_name -> anyserver.docs.Binary
	7, // 5: anyserver.docs.Media.mime_type:type_name -> openformat.v1.MimeType
	0, // 6: anyserver.docs.Docs.Source:input_type -> anyserver.docs.SourceRequest
	1, // 7: anyserver.docs.Docs.Source:output_type -> anyserver.docs.SourceCode
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_docs_proto_init() }
func file_docs_proto_init() {
	if File_docs_proto != nil {
		return
	}
	file_docs_proto_msgTypes[1].OneofWrappers = []any{
		(*SourceCode_Path)(nil),
		(*SourceCode_Code)(nil),
		(*SourceCode_Media)(nil),
		(*SourceCode_Data)(nil),
		(*SourceCode_Binary)(nil),
	}
	file_docs_proto_msgTypes[5].OneofWrappers = []any{
		(*Data_TypeUrl)(nil),
		(*Data_Text)(nil),
		(*Data_FileName)(nil),
		(*Data_More)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_rawDesc), len(file_docs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_goTypes,
		DependencyIndexes: file_docs_proto_depIdxs,
		MessageInfos:      file_docs_proto_msgTypes,
	}.Build()
	File_docs_proto = out.File
	file_docs_proto_goTypes = nil
	file_docs_proto_depIdxs = nil
}
