// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: metrics.proto

package metricspb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootStatus int32

const (
	BootStatus_BOOT_UNKNOWN  BootStatus = 0
	BootStatus_BOOT_STARTED  BootStatus = 1
	BootStatus_BOOT_COMPLETE BootStatus = 2
)

// Enum value maps for BootStatus.
var (
	BootStatus_name = map[int32]string{
		0: "BOOT_UNKNOWN",
		1: "BOOT_STARTED",
		2: "BOOT_COMPLETE",
	}
	BootStatus_value = map[string]int32{
		"BOOT_UNKNOWN":  0,
		"BOOT_STARTED":  1,
		"BOOT_COMPLETE": 2,
	}
)

func (x BootStatus) Enum() *BootStatus {
	p := new(BootStatus)
	*p = x
	return p
}

func (x BootStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BootStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_proto_enumTypes[0].Descriptor()
}

func (BootStatus) Type() protoreflect.EnumType {
	return &file_metrics_proto_enumTypes[0]
}

func (x BootStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BootStatus.Descriptor instead.
func (BootStatus) EnumDescriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

type StaticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticRequest) Reset() {
	*x = StaticRequest{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticRequest) ProtoMessage() {}

func (x *StaticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticRequest.ProtoReflect.Descriptor instead.
func (*StaticRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

type StaticResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	GoVersion     string                 `protobuf:"bytes,3,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	BuildLog      *BuildLog              `protobuf:"bytes,6,opt,name=build_log,json=buildLog,proto3" json:"build_log,omitempty"`
	TestLog       *TestLog               `protobuf:"bytes,7,opt,name=test_log,json=testLog,proto3" json:"test_log,omitempty"`
	BootLog       *BootLog               `protobuf:"bytes,8,opt,name=boot_log,json=bootLog,proto3" json:"boot_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticResponse) Reset() {
	*x = StaticResponse{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticResponse) ProtoMessage() {}

func (x *StaticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticResponse.ProtoReflect.Descriptor instead.
func (*StaticResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *StaticResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *StaticResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StaticResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *StaticResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *StaticResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *StaticResponse) GetBuildLog() *BuildLog {
	if x != nil {
		return x.BuildLog
	}
	return nil
}

func (x *StaticResponse) GetTestLog() *TestLog {
	if x != nil {
		return x.TestLog
	}
	return nil
}

func (x *StaticResponse) GetBootLog() *BootLog {
	if x != nil {
		return x.BootLog
	}
	return nil
}

type ActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveRequest) Reset() {
	*x = ActiveRequest{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveRequest) ProtoMessage() {}

func (x *ActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveRequest.ProtoReflect.Descriptor instead.
func (*ActiveRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

type ActiveResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Goroutines     int64                  `protobuf:"varint,1,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	HeapAllocBytes int64                  `protobuf:"varint,2,opt,name=heap_alloc_bytes,json=heapAllocBytes,proto3" json:"heap_alloc_bytes,omitempty"`
	SysBytes       int64                  `protobuf:"varint,3,opt,name=sys_bytes,json=sysBytes,proto3" json:"sys_bytes,omitempty"`
	NumGc          int64                  `protobuf:"varint,4,opt,name=num_gc,json=numGc,proto3" json:"num_gc,omitempty"` // TODO: add procfs data (cpu, open fds, etc.) after compaction
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActiveResponse) Reset() {
	*x = ActiveResponse{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveResponse) ProtoMessage() {}

func (x *ActiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveResponse.ProtoReflect.Descriptor instead.
func (*ActiveResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *ActiveResponse) GetGoroutines() int64 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *ActiveResponse) GetHeapAllocBytes() int64 {
	if x != nil {
		return x.HeapAllocBytes
	}
	return 0
}

func (x *ActiveResponse) GetSysBytes() int64 {
	if x != nil {
		return x.SysBytes
	}
	return 0
}

func (x *ActiveResponse) GetNumGc() int64 {
	if x != nil {
		return x.NumGc
	}
	return 0
}

type LifetimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifetimeRequest) Reset() {
	*x = LifetimeRequest{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifetimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifetimeRequest) ProtoMessage() {}

func (x *LifetimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifetimeRequest.ProtoReflect.Descriptor instead.
func (*LifetimeRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

type LifetimeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BootTime         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	TotalRequests    int64                  `protobuf:"varint,3,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	RequestsByPath   map[string]int64       `protobuf:"bytes,4,rep,name=requests_by_path,json=requestsByPath,proto3" json:"requests_by_path,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RequestsByStatus map[int32]int64        `protobuf:"bytes,5,rep,name=requests_by_status,json=requestsByStatus,proto3" json:"requests_by_status,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LifetimeResponse) Reset() {
	*x = LifetimeResponse{}
	mi := &file_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifetimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifetimeResponse) ProtoMessage() {}

func (x *LifetimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifetimeResponse.ProtoReflect.Descriptor instead.
func (*LifetimeResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *LifetimeResponse) GetBootTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BootTime
	}
	return nil
}

func (x *LifetimeResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *LifetimeResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *LifetimeResponse) GetRequestsByPath() map[string]int64 {
	if x != nil {
		return x.RequestsByPath
	}
	return nil
}

func (x *LifetimeResponse) GetRequestsByStatus() map[int32]int64 {
	if x != nil {
		return x.RequestsByStatus
	}
	return nil
}

type HistoricalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowSeconds int32                  `protobuf:"varint,1,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"` // how far back to look
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalRequest) Reset() {
	*x = HistoricalRequest{}
	mi := &file_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalRequest) ProtoMessage() {}

func (x *HistoricalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalRequest.ProtoReflect.Descriptor instead.
func (*HistoricalRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *HistoricalRequest) GetWindowSeconds() int32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

type HistoricalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO: implement time-series buckets after compaction
	Placeholder   string `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalResponse) Reset() {
	*x = HistoricalResponse{}
	mi := &file_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalResponse) ProtoMessage() {}

func (x *HistoricalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalResponse.ProtoReflect.Descriptor instead.
func (*HistoricalResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *HistoricalResponse) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type BuildLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildLog) Reset() {
	*x = BuildLog{}
	mi := &file_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLog) ProtoMessage() {}

func (x *BuildLog) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLog.ProtoReflect.Descriptor instead.
func (*BuildLog) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *BuildLog) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

type TestLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestLog) Reset() {
	*x = TestLog{}
	mi := &file_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestLog) ProtoMessage() {}

func (x *TestLog) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestLog.ProtoReflect.Descriptor instead.
func (*TestLog) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *TestLog) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

type BootEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        BootStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=anyserver.metrics.BootStatus" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootEvent) Reset() {
	*x = BootEvent{}
	mi := &file_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootEvent) ProtoMessage() {}

func (x *BootEvent) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootEvent.ProtoReflect.Descriptor instead.
func (*BootEvent) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *BootEvent) GetStatus() BootStatus {
	if x != nil {
		return x.Status
	}
	return BootStatus_BOOT_UNKNOWN
}

func (x *BootEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type BootLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*BootEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootLog) Reset() {
	*x = BootLog{}
	mi := &file_metrics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootLog) ProtoMessage() {}

func (x *BootLog) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootLog.ProtoReflect.Descriptor instead.
func (*BootLog) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{11}
}

func (x *BootLog) GetEvents() []*BootEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\x11anyserver.metrics\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n" +
	"\rStaticRequest\"\xab\x02\n" +
	"\x0eStaticResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"go_version\x18\x03 \x01(\tR\tgoVersion\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x128\n" +
	"\tbuild_log\x18\x06 \x01(\v2\x1b.anyserver.metrics.BuildLogR\bbuildLog\x125\n" +
	"\btest_log\x18\a \x01(\v2\x1a.anyserver.metrics.TestLogR\atestLog\x125\n" +
	"\bboot_log\x18\b \x01(\v2\x1a.anyserver.metrics.BootLogR\abootLog\"\x0f\n" +
	"\rActiveRequest\"\x8e\x01\n" +
	"\x0eActiveResponse\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x01 \x01(\x03R\n" +
	"goroutines\x12(\n" +
	"\x10heap_alloc_bytes\x18\x02 \x01(\x03R\x0eheapAllocBytes\x12\x1b\n" +
	"\tsys_bytes\x18\x03 \x01(\x03R\bsysBytes\x12\x15\n" +
	"\x06num_gc\x18\x04 \x01(\x03R\x05numGc\"\x11\n" +
	"\x0fLifetimeRequest\"\xed\x03\n" +
	"\x10LifetimeResponse\x127\n" +
	"\tboot_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bbootTime\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12%\n" +
	"\x0etotal_requests\x18\x03 \x01(\x03R\rtotalRequests\x12a\n" +
	"\x10requests_by_path\x18\x04 \x03(\v27.anyserver.metrics.LifetimeResponse.RequestsByPathEntryR\x0erequestsByPath\x12g\n" +
	"\x12requests_by_status\x18\x05 \x03(\v29.anyserver.metrics.LifetimeResponse.RequestsByStatusEntryR\x10requestsByStatus\x1aA\n" +
	"\x13RequestsByPathEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aC\n" +
	"\x15RequestsByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\":\n" +
	"\x11HistoricalRequest\x12%\n" +
	"\x0ewindow_seconds\x18\x01 \x01(\x05R\rwindowSeconds\"6\n" +
	"\x12HistoricalResponse\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder\"\"\n" +
	"\bBuildLog\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\"!\n" +
	"\aTestLog\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\"|\n" +
	"\tBootEvent\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.anyserver.metrics.BootStatusR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"?\n" +
	"\aBootLog\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.anyserver.metrics.BootEventR\x06events*C\n" +
	"\n" +
	"BootStatus\x12\x10\n" +
	"\fBOOT_UNKNOWN\x10\x00\x12\x10\n" +
	"\fBOOT_STARTED\x10\x01\x12\x11\n" +
	"\rBOOT_COMPLETE\x10\x022\xc1\x03\n" +
	"\aMetrics\x12f\n" +
	"\x06Static\x12 .anyserver.metrics.StaticRequest\x1a!.anyserver.metrics.StaticResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/metrics/static\x12f\n" +
	"\x06Active\x12 .anyserver.metrics.ActiveRequest\x1a!.anyserver.metrics.ActiveResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/metrics/active\x12n\n" +
	"\bLifetime\x12\".anyserver.metrics.LifetimeRequest\x1a#.anyserver.metrics.LifetimeResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/metrics/lifetime\x12v\n" +
	"\n" +
	"Historical\x12$.anyserver.metrics.HistoricalRequest\x1a%.anyserver.metrics.HistoricalResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/metrics/historicalB:Z8github.com/accretional/anyserver/proto/metrics;metricspbb\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_metrics_proto_goTypes = []any{
	(BootStatus)(0),               // 0: anyserver.metrics.BootStatus
	(*StaticRequest)(nil),         // 1: anyserver.metrics.StaticRequest
	(*StaticResponse)(nil),        // 2: anyserver.metrics.StaticResponse
	(*ActiveRequest)(nil),         // 3: anyserver.metrics.ActiveRequest
	(*ActiveResponse)(nil),        // 4: anyserver.metrics.ActiveResponse
	(*LifetimeRequest)(nil),       // 5: anyserver.metrics.LifetimeRequest
	(*LifetimeResponse)(nil),      // 6: anyserver.metrics.LifetimeResponse
	(*HistoricalRequest)(nil),     // 7: anyserver.metrics.HistoricalRequest
	(*HistoricalResponse)(nil),    // 8: anyserver.metrics.HistoricalResponse
	(*BuildLog)(nil),              // 9: anyserver.metrics.BuildLog
	(*TestLog)(nil),               // 10: anyserver.metrics.TestLog
	(*BootEvent)(nil),             // 11: anyserver.metrics.BootEvent
	(*BootLog)(nil),               // 12: anyserver.metrics.BootLog
	nil,                           // 13: anyserver.metrics.LifetimeResponse.RequestsByPathEntry
	nil,                           // 14: anyserver.metrics.LifetimeResponse.RequestsByStatusEntry
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_metrics_proto_depIdxs = []int32{
	9,  // 0: anyserver.metrics.StaticResponse.build_log:type_name -> anyserver.metrics.BuildLog
	10, // 1: anyserver.metrics.StaticResponse.test_log:type_name -> anyserver.metrics.TestLog
	12, // 2: anyserver.metrics.StaticResponse.boot_log:type_name -> anyserver.metrics.BootLog
	15, // 3: anyserver.metrics.LifetimeResponse.boot_time:type_name -> google.protobuf.Timestamp
	13, // 4: anyserver.metrics.LifetimeResponse.requests_by_path:type_name -> anyserver.metrics.LifetimeResponse.RequestsByPathEntry
	14, // 5: anyserver.metrics.LifetimeResponse.requests_by_status:type_name -> anyserver.metrics.LifetimeResponse.RequestsByStatusEntry
	0,  // 6: anyserver.metrics.BootEvent.status:type_name -> anyserver.metrics.BootStatus
	15, // 7: anyserver.metrics.BootEvent.timestamp:type_name -> google.protobuf.Timestamp
	11, // 8: anyserver.metrics.BootLog.events:type_name -> anyserver.metrics.BootEvent
	1,  // 9: anyserver.metrics.Metrics.Static:input_type -> anyserver.metrics.StaticRequest
	3,  // 10: anyserver.metrics.Metrics.Active:input_type -> anyserver.metrics.ActiveRequest
	5,  // 11: anyserver.metrics.Metrics.Lifetime:input_type -> anyserver.metrics.LifetimeRequest
	7,  // 12: anyserver.metrics.Metrics.Historical:input_type -> anyserver.metrics.HistoricalRequest
	2,  // 13: anyserver.metrics.Metrics.Static:output_type -> anyserver.metrics.StaticResponse
	4,  // 14: anyserver.metrics.Metrics.Active:output_type -> anyserver.metrics.ActiveResponse
	6,  // 15: anyserver.metrics.Metrics.Lifetime:output_type -> anyserver.metrics.LifetimeResponse
	8,  // 16: anyserver.metrics.Metrics.Historical:output_type -> anyserver.metrics.HistoricalResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		EnumInfos:         file_metrics_proto_enumTypes,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
