// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: metrics.proto

package metricspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Metrics_Static_FullMethodName     = "/anyserver.metrics.Metrics/Static"
	Metrics_Active_FullMethodName     = "/anyserver.metrics.Metrics/Active"
	Metrics_Lifetime_FullMethodName   = "/anyserver.metrics.Metrics/Lifetime"
	Metrics_Historical_FullMethodName = "/anyserver.metrics.Metrics/Historical"
)

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsClient interface {
	// Static returns build-time and boot-time metadata (never changes after boot).
	Static(ctx context.Context, in *StaticRequest, opts ...grpc.CallOption) (*StaticResponse, error)
	// Active returns current live server state (connections, goroutines, memory).
	Active(ctx context.Context, in *ActiveRequest, opts ...grpc.CallOption) (*ActiveResponse, error)
	// Lifetime returns cumulative counters since boot (total requests, errors).
	Lifetime(ctx context.Context, in *LifetimeRequest, opts ...grpc.CallOption) (*LifetimeResponse, error)
	// Historical returns time-series data (request rates, latencies over time).
	// TODO: implement after compaction
	Historical(ctx context.Context, in *HistoricalRequest, opts ...grpc.CallOption) (*HistoricalResponse, error)
}

type metricsClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsClient(cc grpc.ClientConnInterface) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) Static(ctx context.Context, in *StaticRequest, opts ...grpc.CallOption) (*StaticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaticResponse)
	err := c.cc.Invoke(ctx, Metrics_Static_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) Active(ctx context.Context, in *ActiveRequest, opts ...grpc.CallOption) (*ActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActiveResponse)
	err := c.cc.Invoke(ctx, Metrics_Active_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) Lifetime(ctx context.Context, in *LifetimeRequest, opts ...grpc.CallOption) (*LifetimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LifetimeResponse)
	err := c.cc.Invoke(ctx, Metrics_Lifetime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) Historical(ctx context.Context, in *HistoricalRequest, opts ...grpc.CallOption) (*HistoricalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoricalResponse)
	err := c.cc.Invoke(ctx, Metrics_Historical_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
// All implementations must embed UnimplementedMetricsServer
// for forward compatibility.
type MetricsServer interface {
	// Static returns build-time and boot-time metadata (never changes after boot).
	Static(context.Context, *StaticRequest) (*StaticResponse, error)
	// Active returns current live server state (connections, goroutines, memory).
	Active(context.Context, *ActiveRequest) (*ActiveResponse, error)
	// Lifetime returns cumulative counters since boot (total requests, errors).
	Lifetime(context.Context, *LifetimeRequest) (*LifetimeResponse, error)
	// Historical returns time-series data (request rates, latencies over time).
	// TODO: implement after compaction
	Historical(context.Context, *HistoricalRequest) (*HistoricalResponse, error)
	mustEmbedUnimplementedMetricsServer()
}

// UnimplementedMetricsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsServer struct{}

func (UnimplementedMetricsServer) Static(context.Context, *StaticRequest) (*StaticResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Static not implemented")
}
func (UnimplementedMetricsServer) Active(context.Context, *ActiveRequest) (*ActiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Active not implemented")
}
func (UnimplementedMetricsServer) Lifetime(context.Context, *LifetimeRequest) (*LifetimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lifetime not implemented")
}
func (UnimplementedMetricsServer) Historical(context.Context, *HistoricalRequest) (*HistoricalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Historical not implemented")
}
func (UnimplementedMetricsServer) mustEmbedUnimplementedMetricsServer() {}
func (UnimplementedMetricsServer) testEmbeddedByValue()                 {}

// UnsafeMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServer will
// result in compilation errors.
type UnsafeMetricsServer interface {
	mustEmbedUnimplementedMetricsServer()
}

func RegisterMetricsServer(s grpc.ServiceRegistrar, srv MetricsServer) {
	// If the following call panics, it indicates UnimplementedMetricsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Metrics_ServiceDesc, srv)
}

func _Metrics_Static_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).Static(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_Static_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).Static(ctx, req.(*StaticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_Active_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).Active(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_Active_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).Active(ctx, req.(*ActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_Lifetime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LifetimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).Lifetime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_Lifetime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).Lifetime(ctx, req.(*LifetimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_Historical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).Historical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_Historical_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).Historical(ctx, req.(*HistoricalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Metrics_ServiceDesc is the grpc.ServiceDesc for Metrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anyserver.metrics.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Static",
			Handler:    _Metrics_Static_Handler,
		},
		{
			MethodName: "Active",
			Handler:    _Metrics_Active_Handler,
		},
		{
			MethodName: "Lifetime",
			Handler:    _Metrics_Lifetime_Handler,
		},
		{
			MethodName: "Historical",
			Handler:    _Metrics_Historical_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics.proto",
}
