// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: resource.proto

package filespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resource is a typed file or stream reference returned by the Files service.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Resource_Document
	//	*Resource_Media
	//	*Resource_Data
	//	*Resource_Socket
	Kind          isResource_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Resource) GetKind() isResource_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Resource) GetDocument() *Document {
	if x != nil {
		if x, ok := x.Kind.(*Resource_Document); ok {
			return x.Document
		}
	}
	return nil
}

func (x *Resource) GetMedia() *Media {
	if x != nil {
		if x, ok := x.Kind.(*Resource_Media); ok {
			return x.Media
		}
	}
	return nil
}

func (x *Resource) GetData() *Data {
	if x != nil {
		if x, ok := x.Kind.(*Resource_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Resource) GetSocket() *Socket {
	if x != nil {
		if x, ok := x.Kind.(*Resource_Socket); ok {
			return x.Socket
		}
	}
	return nil
}

type isResource_Kind interface {
	isResource_Kind()
}

type Resource_Document struct {
	Document *Document `protobuf:"bytes,2,opt,name=document,proto3,oneof"`
}

type Resource_Media struct {
	Media *Media `protobuf:"bytes,3,opt,name=media,proto3,oneof"`
}

type Resource_Data struct {
	Data *Data `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

type Resource_Socket struct {
	Socket *Socket `protobuf:"bytes,5,opt,name=socket,proto3,oneof"`
}

func (*Resource_Document) isResource_Kind() {}

func (*Resource_Media) isResource_Kind() {}

func (*Resource_Data) isResource_Kind() {}

func (*Resource_Socket) isResource_Kind() {}

var File_resource_proto protoreflect.FileDescriptor

const file_resource_proto_rawDesc = "" +
	"\n" +
	"\x0eresource.proto\x12\x0fanyserver.files\x1a\x0edocument.proto\x1a\vmedia.proto\x1a\n" +
	"data.proto\x1a\fsocket.proto\"\xef\x01\n" +
	"\bResource\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x127\n" +
	"\bdocument\x18\x02 \x01(\v2\x19.anyserver.files.DocumentH\x00R\bdocument\x12.\n" +
	"\x05media\x18\x03 \x01(\v2\x16.anyserver.files.MediaH\x00R\x05media\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x15.anyserver.files.DataH\x00R\x04data\x121\n" +
	"\x06socket\x18\x05 \x01(\v2\x17.anyserver.files.SocketH\x00R\x06socketB\x06\n" +
	"\x04kindB6Z4github.com/accretional/anyserver/proto/files;filespbb\x06proto3"

var (
	file_resource_proto_rawDescOnce sync.Once
	file_resource_proto_rawDescData []byte
)

func file_resource_proto_rawDescGZIP() []byte {
	file_resource_proto_rawDescOnce.Do(func() {
		file_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_proto_rawDesc), len(file_resource_proto_rawDesc)))
	})
	return file_resource_proto_rawDescData
}

var file_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_resource_proto_goTypes = []any{
	(*Resource)(nil), // 0: anyserver.files.Resource
	(*Document)(nil), // 1: anyserver.files.Document
	(*Media)(nil),    // 2: anyserver.files.Media
	(*Data)(nil),     // 3: anyserver.files.Data
	(*Socket)(nil),   // 4: anyserver.files.Socket
}
var file_resource_proto_depIdxs = []int32{
	1, // 0: anyserver.files.Resource.document:type_name -> anyserver.files.Document
	2, // 1: anyserver.files.Resource.media:type_name -> anyserver.files.Media
	3, // 2: anyserver.files.Resource.data:type_name -> anyserver.files.Data
	4, // 3: anyserver.files.Resource.socket:type_name -> anyserver.files.Socket
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_resource_proto_init() }
func file_resource_proto_init() {
	if File_resource_proto != nil {
		return
	}
	file_document_proto_init()
	file_media_proto_init()
	file_data_proto_init()
	file_socket_proto_init()
	file_resource_proto_msgTypes[0].OneofWrappers = []any{
		(*Resource_Document)(nil),
		(*Resource_Media)(nil),
		(*Resource_Data)(nil),
		(*Resource_Socket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_proto_rawDesc), len(file_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_proto_goTypes,
		DependencyIndexes: file_resource_proto_depIdxs,
		MessageInfos:      file_resource_proto_msgTypes,
	}.Build()
	File_resource_proto = out.File
	file_resource_proto_goTypes = nil
	file_resource_proto_depIdxs = nil
}
